const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={console,window:{},module:{exports:{}},roundPrice:x=>x==null?null:+Number(x).toFixed(8),emaSeries:(v,n)=>v.map((_,i)=>v.slice(Math.max(0,i-n+1),i+1).reduce((a,b)=>a+b,0)/Math.min(i+1,n)),analyzeMarket:c=>({signal:c.at(-1).close>=c[0].close?'BUY':'SELL',engine:{trend:c.at(-1).close>=c[0].close?'Bullish':'Bearish'},indicators:{atr14:2}})};vm.createContext(ctx);
vm.runInContext(fs.readFileSync('atlas-ai-analysis-layer.js','utf8'),ctx);vm.runInContext(fs.readFileSync('atlas-decision-quality.js','utf8'),ctx);
function candles(start,step,n=240){return Array.from({length:n},(_,i)=>{const close=start+step*i+Math.sin(i/7)*2;return{time:i*3600000,open:close-.5,high:close+2,low:close-2,close,volume:1000+(i%10)*50}})}
const bull=candles(100,0.2),tfs={'1W':bull,'1D':bull,'12H':bull,'6H':bull,'4H':bull,'1H':bull,'30M':bull,'15M':bull};
const packet=ctx.window.ATLAS_AI_ANALYSIS_LAYER.buildAtlasAIAnalysisPacket({asset:{symbol:'BINANCE:BTCUSDT'},timeframes:tfs,masterConviction:{decision:'LONG'},liquidity:{score:60},futures:{score:50},smartMoney:{experimental_score:40}});
assert(packet.trade_geometry);assert.strictEqual(packet.multi_timeframe.higher_timeframe_bias,'BULLISH');assert.strictEqual(packet.multi_timeframe.entry_timing_bias,'BULLISH');assert.strictEqual(packet.trade_geometry.atr14,2);assert(packet.trade_geometry.long.stop_loss<packet.trade_geometry.long.entry_zone[1]);assert(packet.trade_geometry.long.tp1>packet.trade_geometry.long.entry_zone[1]);assert(Array.isArray(packet.trade_geometry.long.target_rrs));assert(packet.trade_geometry.long.decision_rr>=packet.trade_geometry.long.rr);assert.strictEqual(packet.fallback_thesis.decision,'LONG');assert(packet.fallback_thesis.risk_reward>=1.25);assert(packet.fallback_thesis.decision_threshold<=.20);
const synthetic={multi_timeframe:{normalized_bias:.5,higher_timeframe_score:.6,entry_timing_score:.6,higher_timeframe_bias:'BULLISH',entry_timing_bias:'BULLISH',timeframes:{'4H':{historical:{cycle:{phase:'MARKUP / BULL'}}}}},trade_geometry:{volatility_regime:'NORMAL',long:{entry_zone:[100,100],stop_loss:98,tp1:102,tp2:104,tp3:106,rr:1,decision_rr:3}},evidence:{}};const multiTarget=ctx.window.ATLAS_AI_ANALYSIS_LAYER.atlasDeterministicThesis(synthetic);assert.strictEqual(multiTarget.decision,'LONG');assert.strictEqual(multiTarget.risk_reward,3);
const good={...packet.fallback_thesis,decision:'LONG',entry_zone:[140,141],stop_loss:138,take_profit_1:145,risk_reward:2};const ready=ctx.window.ATLAS_DECISION_QUALITY.atlasDecisionQuality(packet,good);assert(ready.trade_readiness_score>=60);
const bad={...packet.fallback_thesis,decision:'LONG',entry_zone:[140,141],stop_loss:139,take_profit_1:141.4,risk_reward:.4};const gated=ctx.window.ATLAS_DECISION_QUALITY.atlasApplyDecisionGate(packet,bad);assert.strictEqual(gated.decision,'WAIT');assert(gated.decision_quality.reasons.some(x=>x.includes('Risk/reward')));
console.log('ATLAS AI trade geometry + readiness tests PASS');
